[build]
  command = "npm run build"
  publish = ".netlify/functions-internal"
  functions = ".netlify/functions-internal"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/render"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"